In [84]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [85]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [86]:
tokenizer = Tokenizer()

In [87]:
tokenizer.fit_on_texts([faqs])

In [88]:
len(tokenizer.word_index)

282

In [89]:
input_sequences = []

In [90]:
for sentence in faqs.split("\n"):
  tokenize_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1, len(tokenize_sentence)):
    input_sequences.append(tokenize_sentence[:i+1])

In [91]:
max_len = max([len(x) for x in input_sequences ])
max_len

57

In [92]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [93]:
padded_input_sequences = pad_sequences(input_sequences, maxlen= max_len, padding="pre")

In [94]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]], dtype=int32)

In [95]:
x = padded_input_sequences[:,:-1]

In [96]:
y = padded_input_sequences[:,-1]

In [97]:
print(x)
print(x.shape)

[[  0   0   0 ...   0   0  93]
 [  0   0   0 ...   0  93   1]
 [  0   0   0 ...   0   0  11]
 ...
 [  0   0   0 ...   0 279  18]
 [  0   0   0 ... 279  18 280]
 [  0   0   0 ...  18 280 281]]
(863, 56)


In [98]:
print(y)
print(y.shape)

[  1  13   7   1  12  42  15  43  53  68  13 147 148  12  94   5  44  29
  95  30   2   8   4  26  44  69   6  31  70  45   7   1  71  72   6   1
  12  71  72   6   1  12   7  54  73  32   1  71  12  42 149  70  54  31
  55 150   7   1  96   6   1  68  13   9  19 151   1 152 153 154 155  15
  43  53 156  15  43  53  15 159  74 160  98  99  10 163   1 164  96  76
  77 100  33  14 165  33  43  53  68  13 166 101  74  20 102  19   5  78
   6  21  13 102  20 101  74 167  56  46   5  78   6  21 168 169  22   3
 104   5 105  34   9   3  47   5 106   6   1  34  16  35  17  56 170  32
 107  22   2 104   5  34   2  10 171 172  20  57   1 106  10   3 173   1
 108 174  21  58 176   4  79  45  59  45 109 177   6   1  12  77 178  58
  60 179 180 181 182 183 184 185   7   1 109  72   6  16   1 105  17  16
   1  17 187 110 188   7   1 189 190  59   1 191 192   1  17   9   3  19
 194  93   1 195 108   9  47   5  61  62  35 196 197 198  36  34  49   2
 199   5  36 200   3  28  21  12  22   3  23  62   

In [99]:
from tensorflow.keras.utils import to_categorical

In [100]:
y = to_categorical(y, num_classes=283)

In [101]:
y.shape

(863, 283)

In [102]:
x.shape

(863, 56)

In [103]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [104]:
model = Sequential()
model.add(Embedding(283, 100, input_length=56))
model.add(LSTM(150))
model.add(Dense(283, activation='softmax'))

In [105]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [106]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 56, 100)           28300     
                                                                 
 lstm_10 (LSTM)              (None, 150)               150600    
                                                                 
 dense_4 (Dense)             (None, 283)               42733     
                                                                 
Total params: 221633 (865.75 KB)
Trainable params: 221633 (865.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [107]:
model.fit(x,y, epochs=100)

Epoch 1/100
27/27 [==============================] - 6s 101ms/step - loss: 5.4911 - accuracy: 0.0660
Epoch 2/100
27/27 [==============================] - 3s 102ms/step - loss: 5.1066 - accuracy: 0.0776
Epoch 3/100
27/27 [==============================] - 3s 102ms/step - loss: 5.0169 - accuracy: 0.0776
Epoch 4/100
27/27 [==============================] - 4s 153ms/step - loss: 4.9713 - accuracy: 0.0776
Epoch 5/100
27/27 [==============================] - 3s 105ms/step - loss: 4.9081 - accuracy: 0.0788
Epoch 6/100
27/27 [==============================] - 3s 103ms/step - loss: 4.7835 - accuracy: 0.0800
Epoch 7/100
27/27 [==============================] - 3s 102ms/step - loss: 4.6221 - accuracy: 0.1078
Epoch 8/100
27/27 [==============================] - 4s 154ms/step - loss: 4.4152 - accuracy: 0.1275
Epoch 9/100
27/27 [==============================] - 3s 101ms/step - loss: 4.2027 - accuracy: 0.1680
Epoch 10/100
27/27 [==============================] - 3s 102ms/step - loss: 3.9752 - accura

In [121]:
import time
import numpy as np

text = "I am Ankit"

for i in range(50):
  #tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  #padding
  padded_token_text = pad_sequences([token_text], maxlen = 56, padding="pre")
  #predict
  pos = np.argmax(model.predict(padded_token_text))

  for word, index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 [==============================] - 0s 34ms/step
I am Ankit living
1/1 [==============================] - 0s 34ms/step
I am Ankit living outside
1/1 [==============================] - 0s 48ms/step
I am Ankit living outside india
1/1 [==============================] - 0s 35ms/step
I am Ankit living outside india and
1/1 [==============================] - 0s 31ms/step
I am Ankit living outside india and i
1/1 [==============================] - 0s 32ms/step
I am Ankit living outside india and i am
1/1 [==============================] - 0s 31ms/step
I am Ankit living outside india and i am not
1/1 [==============================] - 0s 45ms/step
I am Ankit living outside india and i am not able
1/1 [==============================] - 0s 37ms/step
I am Ankit living outside india and i am not able to
1/1 [==============================] - 0s 35ms/step
I am Ankit living outside india and i am not able to make
1/1 [==============================] - 0s 34ms/step
I am Ankit living outside india